-- Remove all rules for Plan Submitted
DELETE FROM workflow_edit_rule WHERE project_status = 'Plan Submitted';

-- Add new Plan Submitted rules
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('standardNetwork', 'PROJECT', 'Plan Submitted', '/dtra/project/standard_network/edit/before_fulfill_wp_order', 'STANDARD_NETWORK_EDIT_BEFORE_FULFILL_WP_ORDER');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('sapProjectId', 'PROJECT', 'Plan Submitted', '/dtra/project/sap_project_id/edit/before_fulfill_wp_order', 'SAP_PROJECT_ID_EDIT_BEFORE_FULFILL_WP_ORDER');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('name', 'WBS', 'Plan Submitted', '/dtra/project/name/edit/before_closed_cancelled', 'NAME_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('label', 'WBS', 'Plan Submitted', '/dtra/project/label/edit/before_closed_cancelled', 'LABEL_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('site', 'WBS', 'Plan Submitted', '/dtra/project/site/edit/before_closed_cancelled', 'SITE_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('comments', 'WBS', 'Plan Submitted', '/dtra/project/comments/edit/before_closed_cancelled', 'COMMENTS_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('technicalInput', 'WBS', 'Plan Submitted', '/dtra/project/technical_input/edit/before_closed_cancelled', 'TECHNICAL_INPUT_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('technicalOutput', 'WBS', 'Plan Submitted', '/dtra/project/technical_output/edit/before_closed_cancelled', 'TECHNICAL_OUTPUT_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('comments', 'WP', 'Plan Submitted', '/dtra/project/comments/edit/before_closed_cancelled', 'COMMENTS_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('technicalInput', 'WP', 'Plan Submitted', '/dtra/project/technical_input/edit/before_closed_cancelled', 'TECHNICAL_INPUT_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('technicalOutput', 'WP', 'Plan Submitted', '/dtra/project/technical_output/edit/before_closed_cancelled', 'TECHNICAL_OUTPUT_EDIT_BEFORE_CLOSED_CANCELLED');

-- Add Plan Rework Preparation rules (same as previous Plan Submitted rules)
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('standardNetwork', 'PROJECT', 'Plan Rework Preparation', '/dtra/project/standard_network/edit/before_fulfill_wp_order', 'STANDARD_NETWORK_EDIT_BEFORE_FULFILL_WP_ORDER');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('sapProjectId', 'PROJECT', 'Plan Rework Preparation', '/dtra/project/sap_project_id/edit/before_fulfill_wp_order', 'SAP_PROJECT_ID_EDIT_BEFORE_FULFILL_WP_ORDER');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('name', 'WBS', 'Plan Rework Preparation', '/dtra/project/name/edit/before_closed_cancelled', 'NAME_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('label', 'WBS', 'Plan Rework Preparation', '/dtra/project/label/edit/before_closed_cancelled', 'LABEL_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('site', 'WBS', 'Plan Rework Preparation', '/dtra/project/site/edit/before_closed_cancelled', 'SITE_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('comments', 'WBS', 'Plan Rework Preparation', '/dtra/project/comments/edit/before_closed_cancelled', 'COMMENTS_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('technicalInput', 'WBS', 'Plan Rework Preparation', '/dtra/project/technical_input/edit/before_closed_cancelled', 'TECHNICAL_INPUT_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('technicalOutput', 'WBS', 'Plan Rework Preparation', '/dtra/project/technical_output/edit/before_closed_cancelled', 'TECHNICAL_OUTPUT_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('comments', 'WP', 'Plan Rework Preparation', '/dtra/project/comments/edit/before_closed_cancelled', 'COMMENTS_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('technicalInput', 'WP', 'Plan Rework Preparation', '/dtra/project/technical_input/edit/before_closed_cancelled', 'TECHNICAL_INPUT_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('technicalOutput', 'WP', 'Plan Rework Preparation', '/dtra/project/technical_output/edit/before_closed_cancelled', 'TECHNICAL_OUTPUT_EDIT_BEFORE_CLOSED_CANCELLED');


INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('startDate', 'WBS', 'Plan Rework Preparation', '/dtra/project/start_date/edit/plan_rework_preparation', 'START_DATE_EDIT_PLAN_REWORK_PREPARATION');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('dueDate', 'WBS', 'Plan Rework Preparation', '/dtra/project/due_date/edit/plan_rework_preparation', 'DUE_DATE_EDIT_PLAN_REWORK_PREPARATION');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('subNetwork', 'WBS', 'Plan Rework Preparation', '/dtra/project/sub_network/edit/plan_rework_preparation', 'SUB_NETWORK_EDIT_PLAN_REWORK_PREPARATION');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('networkActivity', 'WBS', 'Plan Rework Preparation', '/dtra/project/network_activity/edit/plan_rework_preparation', 'NETWORK_ACTIVITY_EDIT_PLAN_REWORK_PREPARATION');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('purchaseOrder', 'WBS', 'Plan Rework Preparation', '/dtra/project/purchase_order/edit/plan_rework_preparation', 'PURCHASE_ORDER_EDIT_PLAN_REWORK_PREPARATION');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('operationalActivity', 'WBS', 'Plan Rework Preparation', '/dtra/project/operational_activity/edit/plan_rework_preparation', 'OPERATIONAL_ACTIVITY_EDIT_PLAN_REWORK_PREPARATION');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('startDate', 'WP', 'Plan Rework Preparation', '/dtra/project/start_date/edit/plan_rework_preparation', 'START_DATE_EDIT_PLAN_REWORK_PREPARATION');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('dueDate', 'WP', 'Plan Rework Preparation', '/dtra/project/due_date/edit/plan_rework_preparation', 'DUE_DATE_EDIT_PLAN_REWORK_PREPARATION');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('networkActivity', 'WP', 'Plan Rework Preparation', '/dtra/project/network_activity/edit/plan_rework_preparation', 'NETWORK_ACTIVITY_EDIT_PLAN_REWORK_PREPARATION');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('purchaseOrder', 'WP', 'Plan Rework Preparation', '/dtra/project/purchase_order/edit/plan_rework_preparation', 'PURCHASE_ORDER_EDIT_PLAN_REWORK_PREPARATION');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('operationalActivity', 'WP', 'Plan Rework Preparation', '/dtra/project/operational_activity/edit/plan_rework_preparation', 'OPERATIONAL_ACTIVITY_EDIT_PLAN_REWORK_PREPARATION');


-- Add rules for Plan Reworked
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('bundling', 'PROJECT', 'Plan Reworked', '/dtra/project/bundling/edit/plan_reworked', 'BUNDLING_EDIT_PLAN_REWORKED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('standardNetwork', 'PROJECT', 'Plan Reworked', '/dtra/project/standard_network/edit/before_fulfill_wp_order', 'STANDARD_NETWORK_EDIT_BEFORE_FULFILL_WP_ORDER');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('sapProjectId', 'PROJECT', 'Plan Reworked', '/dtra/project/sap_project_id/edit/before_fulfill_wp_order', 'SAP_PROJECT_ID_EDIT_BEFORE_FULFILL_WP_ORDER');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('name', 'WBS', 'Plan Reworked', '/dtra/project/name/edit/before_closed_cancelled', 'NAME_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('label', 'WBS', 'Plan Reworked', '/dtra/project/label/edit/before_closed_cancelled', 'LABEL_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('site', 'WBS', 'Plan Reworked', '/dtra/project/site/edit/before_closed_cancelled', 'SITE_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('comments', 'WBS', 'Plan Reworked', '/dtra/project/comments/edit/before_closed_cancelled', 'COMMENTS_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('startDate', 'WBS', 'Plan Reworked', '/dtra/project/start_date/edit/plan_reworked', 'START_DATE_EDIT_PLAN_REWORKED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('dueDate', 'WBS', 'Plan Reworked', '/dtra/project/due_date/edit/plan_reworked', 'DUE_DATE_EDIT_PLAN_REWORKED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('technicalInput', 'WBS', 'Plan Reworked', '/dtra/project/technical_input/edit/before_closed_cancelled', 'TECHNICAL_INPUT_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('technicalOutput', 'WBS', 'Plan Reworked', '/dtra/project/technical_output/edit/before_closed_cancelled', 'TECHNICAL_OUTPUT_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('comments', 'WP', 'Plan Reworked', '/dtra/project/comments/edit/before_closed_cancelled', 'COMMENTS_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('technicalInput', 'WP', 'Plan Reworked', '/dtra/project/technical_input/edit/before_closed_cancelled', 'TECHNICAL_INPUT_EDIT_BEFORE_CLOSED_CANCELLED');
INSERT INTO workflow_edit_rule (field, level, project_status, permission, normalized_permission) VALUES ('technicalOutput', 'WP', 'Plan Reworked', '/dtra/project/technical_output/edit/before_closed_cancelled', 'TECHNICAL_OUTPUT_EDIT_BEFORE_CLOSED_CANCELLED');
